name: Deploy to AWS App Runner

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
     
    - name: Deploy to App Runner
      run: |
        # Check service status
        STATUS=$(aws apprunner describe-service --service-arn ${{ secrets.APPRUNNER_SERVICE_ARN }} --query 'Service.Status' --output text)
        echo "Service status: $STATUS"
        
        if [ "$STATUS" = "RUNNING" ]; then
          echo "Service is running, starting deployment..."
          aws apprunner start-deployment --service-arn ${{ secrets.APPRUNNER_SERVICE_ARN }}
        else
          echo "Service is not in RUNNING state. Current status: $STATUS"
          echo "Please wait for the service to be in RUNNING state before triggering deployment."
          exit 1
        fi